<a href="https://colab.research.google.com/github/Assaoka/Decolar--Introducao_a_Ciencia_de_Dados/blob/main/%5B%20%205%20%5D%20M%C3%B3dulos%20e%20Introdu%C3%A7%C3%A3o%20ao%20Pandas/M%C3%B3dulos%20e%20Introdu%C3%A7%C3%A3o%20ao%20Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 5: O Kit do Treinador Pokémon: Capturando e Inspecionando Dados

Hoje vamos dar um salto gigantesco em nossas habilidades. Vamos aprender a usar "poderes" que outros programadores criaram e a trabalhar com dados de verdade, que ficam salvos no computador!

### 1. O que são Módulos (ou Bibliotecas)?

Imagine que você quer construir um robô. Você não precisa inventar o parafuso, a roda ou o motor do zero, certo? Você usa peças que já existem!

Na programação, é a mesma coisa. Um **módulo** (ou **biblioteca**) é um conjunto de "peças" — funções e ferramentas prontas — que outros programadores criaram e disponibilizaram para nós. Em vez de reinventar a roda, nós importamos uma biblioteca e usamos suas ferramentas.

Um dos principais motivos para a popularidade do Python é a enorme quantidade de bibliotecas disponíveis para praticamente qualquer tarefa que você possa imaginar: desde análise de dados, inteligência artificial, até desenvolvimento web e jogos.

Hoje, vamos usar a biblioteca mais famosa para análise de dados: o **Pandas**.

### 2. O que é o Pandas?

O **Pandas** é uma biblioteca focada em trabalhar com **dados tabulares** (pense em tabelas do Excel ou do Google Sheets). Ele vem com dezenas de funções prontas que nos ajudam a ler, manipular, analisar e até salvar esses dados de forma muito fácil e eficiente.

Para começar a usá-lo, nosso primeiro passo é sempre o mesmo: importar a biblioteca.

In [ ]:
# Vamos importar a biblioteca pandas e dar a ela o apelido de 'pd'
# Este é um padrão universal, todo cientista de dados faz isso!
import pandas as pd

### 3. De onde vêm os dados? O formato CSV

Nossos programas até agora só guardavam informações enquanto estavam rodando (na memória RAM). Se fechássemos o programa, tudo era perdido. Para trabalhar com dados de verdade, precisamos salvá-los de forma permanente (no HD).

Uma das formas mais comuns de salvar dados tabulares é no formato **CSV** (_Comma-Separated Values_, ou Valores Separados por Vírgula).

Abra um arquivo CSV no bloco de notas e você verá algo assim:

```csv
Name,National Dex #,Primary Typing,Secondary Typing,Secondary Typing Flag,Generation,Legendary Status,Form,Alt Form Flag,Evolution Stage,Number of Evolution,Color ID,Catch Rate,Height (dm),Weight (hg),Height (in),Weight (lbs),Base Stat Total,Health,Attack,Defense,Special Attack,Special Defense,Speed
bulbasaur,1,grass,poison,True,generation-i,False,Base,False,1,3,green,45,7,69,28,15,318,45,49,49,65,65,45
ivysaur,2,grass,poison,True,generation-i,False,Base,False,2,3,green,45,10,130,39,29,405,60,62,63,80,80,60
venusaur,3,grass,poison,True,generation-i,False,Base,False,3,3,green,45,20,1000,79,220,525,80,82,83,100,100,80
venusaur-mega,3,grass,poison,True,generation-i,True,Mega,True,3,3,green,45,24,1555,94,343,625,80,100,123,122,120,80
charmander,4,fire,,False,generation-i,False,Base,False,1,3,red,45,6,85,24,19,309,39,52,43,60,50,65
charmeleon,5,fire,,False,generation-i,False,Base,False,2,3,red,45,11,190,43,42,405,58,64,58,80,65,80
charizard,6,fire,flying,True,generation-i,False,Base,False,3,3,red,45,17,905,67,200,534,78,84,78,109,85,100
charizard-mega-x,6,fire,dragon,True,generation-i,True,Mega X,True,3,3,red,45,17,1105,67,244,634,78,130,111,130,85,100
charizard-mega-y,6,fire,flying,True,generation-i,True,Mega Y,True,3,3,red,45,17,1005,67,222,634,78,104,78,159,115,100
squirtle,7,water,,False,generation-i,False,Base,False,1,3,blue,45,5,90,20,20,314,44,48,65,50,64,43
wartortle,8,water,,False,generation-i,False,Base,False,2,3,blue,45,10,225,39,50,405,59,63,80,65,80,58
blastoise,9,water,,False,generation-i,False,Base,False,3,3,blue,45,16,855,63,188,530,79,83,100,85,105,78
blastoise-mega,9,water,,False,generation-i,True,Mega,True,3,3,blue,45,16,1011,63,223,630,79,103,120,135,115,78
```

Cada linha é uma linha da tabela, e as vírgulas separam os valores de cada coluna. Simples, mas poderoso!

O Pandas consegue ler esses arquivos e transformá-los magicamente em uma tabela superpoderosa chamada **DataFrame**.

In [ ]:
# O Pandas lê o arquivo CSV e cria nosso DataFrame.
# Vamos usar o comando display() para visualizá-lo de forma mais bonita no Colab.
endereco = '../pokemon.csv'
df = pd.read_csv(endereco)
print(df)

                    Name  National Dex # Primary Typing Secondary Typing  \
0              bulbasaur               1          grass           poison
1                ivysaur               2          grass           poison
2               venusaur               3          grass           poison
3          venusaur-mega               3          grass           poison
4             charmander               4           fire              NaN
...                  ...             ...            ...              ...
1179          iron-crown            1023          steel          psychic
1180           terapagos            1024         normal              NaN
1181  terapagos-terastal            1024         normal              NaN
1182   terapagos-stellar            1024         normal              NaN
1183           pecharunt            1025         poison            ghost

      Secondary Typing Flag     Generation  Legendary Status      Form  \
0                      True   generation-i             False      Base
1                      True   generation-i             False      Base
2                      True   generation-i             False      Base
3                      True   generation-i              True      Mega
4                     False   generation-i             False      Base
...                     ...            ...               ...       ...
1179                   True  generation-ix              True      Base
1180                  False  generation-ix              True      Base
1181                  False  generation-ix              True  Terastal
1182                  False  generation-ix              True   Stellar
1183                   True  generation-ix              True      Base

      Alt Form Flag  Evolution Stage  ...  Weight (hg) Height (in)  \
0             False                1  ...           69          28
1             False                2  ...          130          39
2             False                3  ...         1000          79
3              True                3  ...         1555          94
4             False                1  ...           85          24
...             ...              ...  ...          ...         ...
1179          False                1  ...         1560          63
1180          False                1  ...           65           8
1181           True                1  ...          160          12
1182           True                1  ...          770          67
1183          False                1  ...            3          12

      Weight (lbs)  Base Stat Total  Health  Attack  Defense  Special Attack  \
0               15              318      45      49       49              65
1               29              405      60      62       63              80
2              220              525      80      82       83             100
3              343              625      80     100      123             122
4               19              309      39      52       43              60
...            ...              ...     ...     ...      ...             ...
1179           344              590      90      72      100             122
1180            14              450      90      65       85              65
1181            35              600      95      95      110             105
1182           170              700     160     105      110             130
1183             1              600      88      88      160              88

      Special Defense  Speed
0                  65     45
1                  80     60
2                 100     80
3                 120     80
4                  50     65
...               ...    ...
1179              108     98
1180               85     60
1181              110     85
1182              110     85
1183               88     88

[1184 rows x 24 columns]

O comando `display()` é usado para mostrar o DataFrame de uma forma mais bonita, especialmente em ambientes como o Jupyter Notebook ou Google Colab. Ele formata a saída para que pareça uma tabela, facilitando a visualização dos dados.

In [ ]:
display(df)

,Name,National Dex #,Primary Typing,Secondary Typing,Secondary Typing Flag,Generation,Legendary Status,Form,Alt Form Flag,Evolution Stage,...,Weight (hg),Height (in),Weight (lbs),Base Stat Total,Health,Attack,Defense,Special Attack,Special Defense,Speed
0,bulbasaur,1,grass,poison,True,generation-i,False,Base,False,1,...,69,28,15,318,45,49,49,65,65,45
1,ivysaur,2,grass,poison,True,generation-i,False,Base,False,2,...,130,39,29,405,60,62,63,80,80,60
2,venusaur,3,grass,poison,True,generation-i,False,Base,False,3,...,1000,79,220,525,80,82,83,100,100,80
3,venusaur-mega,3,grass,poison,True,generation-i,True,Mega,True,3,...,1555,94,343,625,80,100,123,122,120,80
4,charmander,4,fire,NaN,False,generation-i,False,Base,False,1,...,85,24,19,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1179,iron-crown,1023,steel,psychic,True,generation-ix,True,Base,False,1,...,1560,63,344,590,90,72,100,122,108,98
1180,terapagos,1024,normal,NaN,False,generation-ix,True,Base,False,1,...,65,8,14,450,90,65,85,65,85,60
1181,terapagos-terastal,1024,normal,NaN,False,generation-ix,True,Terastal,True,1,...,160,12,35,600,95,95,110,105,110,85
1182,terapagos-stellar,1024,normal,NaN,False,generation-ix,True,Stellar,True,1,...,770,67,170,700,160,105,110,130,110,85
1183,pecharunt,1025,poison,ghost,True,generation-ix,True,Base,False,1,...,3,12,1,600,88,88,160,88,88,88

### 4. Inspeção Inicial e Manipulação de Dados

Agora que a nossa Pokédex está carregada no DataFrame `df`, vamos aprender os movimentos de um verdadeiro Mestre de Dados.

#### 4.1. Espiando os Dados: `head`, `tail` e `sample`
- `.head(n)`: Mostra as `n` primeiras linhas (ótimo para ver o começo).   
- `.tail(n)`: Mostra as `n` últimas linhas (ótimo para ver o final).
- `.sample(n)`: Mostra `n` linhas aleatórias (ótimo para ter uma ideia geral).

In [ ]:
# Vendo os 5 primeiros Pokémon
print("--- Início da Pokédex (Head) ---")
display(df.head())

--- Início da Pokédex (Head) ---

,Name,National Dex #,Primary Typing,Secondary Typing,Secondary Typing Flag,Generation,Legendary Status,Form,Alt Form Flag,Evolution Stage,...,Weight (hg),Height (in),Weight (lbs),Base Stat Total,Health,Attack,Defense,Special Attack,Special Defense,Speed
0,bulbasaur,1,grass,poison,True,generation-i,False,Base,False,1,...,69,28,15,318,45,49,49,65,65,45
1,ivysaur,2,grass,poison,True,generation-i,False,Base,False,2,...,130,39,29,405,60,62,63,80,80,60
2,venusaur,3,grass,poison,True,generation-i,False,Base,False,3,...,1000,79,220,525,80,82,83,100,100,80
3,venusaur-mega,3,grass,poison,True,generation-i,True,Mega,True,3,...,1555,94,343,625,80,100,123,122,120,80
4,charmander,4,fire,NaN,False,generation-i,False,Base,False,1,...,85,24,19,309,39,52,43,60,50,65

In [ ]:
# Vendo os 5 últimos Pokémon
print("\n--- Final da Pokédex (Tail) ---")
display(df.tail())

--- Final da Pokédex (Tail) ---

,Name,National Dex #,Primary Typing,Secondary Typing,Secondary Typing Flag,Generation,Legendary Status,Form,Alt Form Flag,Evolution Stage,...,Weight (hg),Height (in),Weight (lbs),Base Stat Total,Health,Attack,Defense,Special Attack,Special Defense,Speed
1179,iron-crown,1023,steel,psychic,True,generation-ix,True,Base,False,1,...,1560,63,344,590,90,72,100,122,108,98
1180,terapagos,1024,normal,NaN,False,generation-ix,True,Base,False,1,...,65,8,14,450,90,65,85,65,85,60
1181,terapagos-terastal,1024,normal,NaN,False,generation-ix,True,Terastal,True,1,...,160,12,35,600,95,95,110,105,110,85
1182,terapagos-stellar,1024,normal,NaN,False,generation-ix,True,Stellar,True,1,...,770,67,170,700,160,105,110,130,110,85
1183,pecharunt,1025,poison,ghost,True,generation-ix,True,Base,False,1,...,3,12,1,600,88,88,160,88,88,88

In [ ]:
# Vendo 5 Pokémon aleatórios
print("\n--- Amostra Aleatória da Pokédex (Sample) ---")
display(df.sample(5))

--- Amostra Aleatória da Pokédex (Sample) ---

,Name,National Dex #,Primary Typing,Secondary Typing,Secondary Typing Flag,Generation,Legendary Status,Form,Alt Form Flag,Evolution Stage,...,Weight (hg),Height (in),Weight (lbs),Base Stat Total,Health,Attack,Defense,Special Attack,Special Defense,Speed
1074,pawmo,922,electric,fighting,True,generation-ix,False,Base,False,2,...,65,16,14,350,60,75,40,50,40,85
837,bergmite,712,ice,NaN,False,generation-vi,False,Base,False,1,...,995,39,219,304,55,69,85,32,35,28
147,lickitung,108,normal,NaN,False,generation-i,False,Base,False,1,...,655,47,144,385,90,55,75,60,75,30
279,teddiursa,216,normal,NaN,False,generation-ii,False,Base,False,1,...,88,24,19,330,60,80,50,50,50,40
243,hoppip,187,grass,flying,True,generation-ii,False,Base,False,1,...,5,16,1,250,35,35,40,35,55,50

#### 4.2. Informações Técnicas: `info` e `shape`
- `.shape`: Nos diz as dimensões da tabela (linhas, colunas).
- `.info()`: Nos dá um raio-x completo, incluindo o tipo de dado de cada coluna e o uso de memória (muito útil para ver se há dados faltando!).

In [ ]:
# Mostra uma tupla com (número_de_linhas, número_de_colunas)
print(f"Nossa Pokédex tem {df.shape[0]} Pokémon e {df.shape[1]} atributos.")

Nossa Pokédex tem 1184 Pokémon e 24 atributos.

In [ ]:
# Exibe o resumo técnico. memory_usage='deep' nos dá um cálculo de memória mais preciso.
print("\n--- Raio-X da Pokédex (Info) ---")
df.info(memory_usage="deep")

--- Raio-X da Pokédex (Info) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1184 entries, 0 to 1183
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   1184 non-null   object
 1   National Dex #         1184 non-null   int64
 2   Primary Typing         1184 non-null   object
 3   Secondary Typing       654 non-null    object
 4   Secondary Typing Flag  1184 non-null   bool
 5   Generation             1184 non-null   object
 6   Legendary Status       1184 non-null   bool
 7   Form                   1184 non-null   object
 8   Alt Form Flag          1184 non-null   bool
 9   Evolution Stage        1184 non-null   int64
 10  Number of Evolution    1184 non-null   int64
 11  Color ID               1184 non-null   object
 12  Catch Rate             1184 non-null   int64
 13  Height (dm)            1184 non-null   int64
 14  Weight (hg)            1184 non-null   int64
 15  Height (in)            1184 non-null   int64
 16  Weight (lbs)           1184 non-null   int64
 17  Base Stat Total        1184 non-null   int64
 18  Health                 1184 non-null   int64
 19  Attack                 1184 non-null   int64
 20  Defense                1184 non-null   int64
 21  Special Attack         1184 non-null   int64
 22  Special Defense        1184 non-null   int64
 23  Speed                  1184 non-null   int64
dtypes: bool(3), int64(15), object(6)
memory usage: 518.7 KB

#### 4.3. Selecionando e Operando com Colunas
Podemos pegar colunas específicas para focar nossa análise e até fazer operações matemáticas com elas!

In [ ]:
# Selecionando uma coluna
df['Name']

0                bulbasaur
1                  ivysaur
2                 venusaur
3            venusaur-mega
4               charmander
               ...
1179            iron-crown
1180             terapagos
1181    terapagos-terastal
1182     terapagos-stellar
1183             pecharunt
Name: Name, Length: 1184, dtype: object

In [ ]:
# Selecionando múltiplas colunas
stats_essenciais = df[['Name', 'Attack', 'Defense', 'Speed']]
print("--- Stats Essenciais ---")
stats_essenciais.head()

--- Stats Essenciais ---

            Name  Attack  Defense  Speed
0      bulbasaur      49       49     45
1        ivysaur      62       63     60
2       venusaur      82       83     80
3  venusaur-mega     100      123     80
4     charmander      52       43     65

In [ ]:
# Podemos criar uma nova coluna! Que tal um 'Total Power' somando Ataque e Defesa?
df['Total Power'] = df['Attack'] + df['Defense'] + df['Speed']
print("\n--- Criamos a coluna 'Total Power' ---")
df[['Name', 'Attack', 'Defense', 'Speed', 'Total Power']].head()

--- Criamos a coluna 'Total Power' ---

            Name  Attack  Defense  Speed  Total Power
0      bulbasaur      49       49     45          143
1        ivysaur      62       63     60          185
2       venusaur      82       83     80          245
3  venusaur-mega     100      123     80          303
4     charmander      52       43     65          160

#### 4.4. Filtrando: A Arte de Fazer Perguntas

E se quisermos encontrar apenas os Pokémon do tipo 'Fire'? Ou os que são da Geração I? Para isso, usamos **filtros**. A sintaxe é: `df[ <condição> ]`.

In [ ]:
# Encontrando todos os Pokémon do tipo Fogo
df_fogo = df[df['Primary Typing'] == 'fire']
print("--- Apenas Pokémon do tipo Fogo ---")
df_fogo.head()

--- Apenas Pokémon do tipo Fogo ---

,Name,National Dex #,Primary Typing,Secondary Typing,Secondary Typing Flag,Generation,Legendary Status,Form,Alt Form Flag,Evolution Stage,...,Height (in),Weight (lbs),Base Stat Total,Health,Attack,Defense,Special Attack,Special Defense,Speed,Total Power
4,charmander,4,fire,NaN,False,generation-i,False,Base,False,1,...,24,19,309,39,52,43,60,50,65,160
5,charmeleon,5,fire,NaN,False,generation-i,False,Base,False,2,...,43,42,405,58,64,58,80,65,80,202
6,charizard,6,fire,flying,True,generation-i,False,Base,False,3,...,67,200,534,78,84,78,109,85,100,262
7,charizard-mega-x,6,fire,dragon,True,generation-i,True,Mega X,True,3,...,67,244,634,78,130,111,130,85,100,341
8,charizard-mega-y,6,fire,flying,True,generation-i,True,Mega Y,True,3,...,67,222,634,78,104,78,159,115,100,282

In [ ]:
# Encontrando Pokémon com Ataque maior que 150
df_super_ataque = df[df['Attack'] > 150]
print("\n--- Apenas Pokémon com Ataque SUPERIOR a 150 ---")
df_super_ataque

--- Apenas Pokémon com Ataque SUPERIOR a 150 ---

,Name,National Dex #,Primary Typing,Secondary Typing,Secondary Typing Flag,Generation,Legendary Status,Form,Alt Form Flag,Evolution Stage,...,Height (in),Weight (lbs),Base Stat Total,Health,Attack,Defense,Special Attack,Special Defense,Speed,Total Power
170,pinsir-mega,127,bug,flying,True,generation-i,True,Mega,True,1,...,67,130,600,65,155,120,65,90,105,380
177,gyarados-mega,130,water,dark,True,generation-i,True,Mega,True,2,...,256,672,640,95,155,109,70,130,81,345
203,mewtwo-mega-x,150,psychic,fighting,True,generation-i,True,Mega X,True,1,...,91,280,780,106,190,100,154,100,130,420
276,heracross-mega,214,bug,fighting,True,generation-ii,True,Mega,True,1,...,67,138,600,80,185,115,40,105,75,375
314,tyranitar-mega,248,rock,dark,True,generation-ii,True,Mega,True,3,...,98,562,700,100,164,150,95,120,71,385
325,blaziken-mega,257,fire,fighting,True,generation-iii,True,Mega,True,3,...,75,115,630,80,160,80,130,80,100,340
361,slaking,289,normal,NaN,False,generation-iii,False,Base,False,3,...,79,288,670,150,160,100,95,65,100,360
438,banette-mega,354,ghost,NaN,False,generation-iii,True,Mega,True,2,...,47,29,555,64,165,75,93,83,75,315
475,groudon-primal,383,ground,fire,True,generation-iii,True,Primal,True,1,...,197,2204,770,100,180,160,150,90,90,430
477,rayquaza-mega,384,dragon,flying,True,generation-iii,True,Mega,True,1,...,425,864,780,105,180,100,180,100,115,395
502,rampardos,409,rock,NaN,False,generation-iv,False,Base,False,2,...,63,226,495,97,165,60,65,50,58,283
542,garchomp-mega,445,dragon,ground,True,generation-iv,True,Mega,True,3,...,75,209,700,108,170,115,120,95,92,377
575,gallade-mega,475,psychic,fighting,True,generation-iv,True,Mega,True,3,...,63,124,618,68,165,95,65,115,110,370
591,regigigas,486,normal,NaN,False,generation-iv,True,Base,False,1,...,146,926,670,110,160,110,80,110,100,370
668,darmanitan-galar-zen,555,ice,fire,True,generation-v,False,Galarian,True,2,...,67,265,540,105,160,55,30,55,135,350
765,kyurem-black,646,dragon,ice,True,generation-v,True,Black,True,1,...,130,717,700,125,170,100,120,90,95,365
849,diancie-mega,719,rock,fairy,True,generation-vi,True,Mega,True,1,...,43,61,700,50,160,110,160,110,110,380
851,hoopa-unbound,720,psychic,dark,True,generation-vi,True,Unbound,True,1,...,256,1080,680,80,160,60,170,130,80,300
941,kartana,798,grass,steel,True,generation-vii,True,Base,False,1,...,12,0,570,59,181,131,59,31,109,421
944,necrozma-dusk,800,psychic,steel,True,generation-vii,True,Dusk,True,1,...,150,1014,680,97,157,127,113,109,77,361
946,necrozma-ultra,800,psychic,dragon,True,generation-vii,True,Ultra,True,1,...,295,507,754,97,167,97,167,97,129,393
1048,calyrex-ice,898,psychic,ice,True,generation-viii,True,Ice,True,1,...,94,1784,680,100,165,150,85,130,50,365
1117,palafin-hero,964,water,NaN,False,generation-ix,False,Hero,True,2,...,71,215,650,100,160,97,106,87,100,357

#### 4.5. Ordenando: Quem é o mais forte?

Depois de filtrar, muitas vezes queremos ordenar os resultados. Usamos `.sort_values()`.

In [ ]:
# Pegando os Pokémon de Fogo e ordenando pelo Ataque, do maior para o menor
df_fogo_mais_forte = df_fogo.sort_values(by='Attack', ascending=False)
print("--- Top 5 Pokémon de Fogo, ordenados pelo Ataque ---")
display(df_fogo_mais_forte.head())

--- Top 5 Pokémon de Fogo, ordenados pelo Ataque ---

,Name,National Dex #,Primary Typing,Secondary Typing,Secondary Typing Flag,Generation,Legendary Status,Form,Alt Form Flag,Evolution Stage,...,Height (in),Weight (lbs),Base Stat Total,Health,Attack,Defense,Special Attack,Special Defense,Speed,Total Power
325,blaziken-mega,257,fire,fighting,True,generation-iii,True,Mega,True,3,...,75,115,630,80,160,80,130,80,100,340
665,darmanitan-standard,555,fire,NaN,False,generation-v,False,Base,False,2,...,51,205,480,105,140,55,30,55,95,290
316,ho-oh,250,fire,flying,True,generation-ii,True,Base,False,1,...,150,439,680,106,130,90,110,154,90,310
7,charizard-mega-x,6,fire,dragon,True,generation-i,True,Mega X,True,3,...,67,244,634,78,130,111,130,85,100,341
184,flareon,136,fire,NaN,False,generation-i,False,Base,False,2,...,35,55,525,65,130,60,95,110,65,255

### 5. Hora dos Exercícios!

Vamos praticar esses novos movimentos.

**1. Os Iniciais da Geração 1:** Crie um DataFrame que contenha apenas Bulbasaur, Charmander e Squirtle.

**2. O Pokémon mais Rápido:** Encontre o Pokémon com o maior valor de `Speed` em todo o dataset.

**3. Pesos Pesados:** Encontre todos os Pokémon que pesam (coluna `Weight (hg)`) mais de 70 kg.

Obs: 1 kg = 10 hg.

**4. Fraqueza Psíquica:** Encontre todos os Pokémon do tipo `Bug` que sejam da `generation-i`.

**5. Top 5 Defensores:** Crie um DataFrame com os 5 Pokémon com a maior `Defense`.

**6. Elite Lendária:** Crie um DataFrame com todos os Pokémon lendários (`Legendary Status` igual a `True`), ordene-os pelo `Base Stat Total` (do maior para o menor) e salve esse DataFrame em um novo arquivo CSV chamado `legendary_pokemon.csv`.